### ISSUE TITLE
Proposal: Inhibitor priority like in Komada

### ISSUE THREAD

**Issue by pedall** [dirigeants/klasa#188]
### Describe the proposal

At the moment we have absolutely no control about the order the inhibitors are run in. And for some ideas there is the scenario needed to run one inhibitor before another and to stop the the whole process 
(to not run the other inhibitors following)

**Comment by Soumil07** [comment]
Isn't there a priority in Inhibitor#options?

**Comment by kyranet** [comment]
@Soumil07 you are referring to [Komada](https://komada.js.org/module-Inhibitor.html#.conf). Klasa doesn't have a property of `priority`, but rather all inhibitors are ran no matter the order.

**Comment by bdistin** [comment]
All inhibitors are run regardless in klasa, unlike komada, so that because it is order-less; if any inhibitor says the command should fail silently, or if there are multiple reasons why not to run the command, all are taken into account.

Inhibitors are meant to be stateless, and not depend on any other inhibitor.
