### ISSUE TITLE
Easy way to disable individual core commands

### ISSUE THREAD

**Issue by jellz** [dirigeants/klasa#344]
### Describe your proposal
I want an easy way to disable individual core commands.

### Usecases for your proposal
I don't want to have the `user-conf` command in my bot. At least not in the near future. There is no nice way to get rid of it, without getting rid of all the other core commands.

### Expected and actual behaviour
**Currently** I'd need to transfer the command file, then set **enabled: false**, then maybe move it into a folder called 'Disabled' or something. That is quite annoying, especially if I wanna make the bot open source. I don't want a random folder with some commands that shouldn't be touched.

I want a way to be able to persistently disable individual core commands globally, that'd work with OSS. You could put it into the Client initialization, maybe?

I really hope this is added, as this issue is really annoying me.
Thanks for reading.

**Comment by ShayBox** [comment]
In master, you can use `disableCorePieces: ['commands']` in client options to disable all built-in commands, you can transfer what you want to keep enabled.

**Comment by jellz** [comment]
There are ~16 core commands, and only ~2 commands I want to disable. That doesn't seem very ideal. Though it is a possible work around, though. Thanks.

**Comment by ShayBox** [comment]
Yeah, it's not a perfect solution, but you're not gonna get an option to disable specific commands only with this framework, they want you to transfer everything :/

**Comment by bdistin** [comment]
I am not too keen on this idea, since it is one thing to skip walking a directory, but another to do O(n^2) searches on every piece loaded to see if it's not supposed to load, instead of the more OOP way where the piece knows if it should load or not (via the enabled property).

Generally speaking, the preferred way of accomplishing this right now is transferring the piece, disabling it (optionally you can remove everything but the constructor portion of the class), and optionally moving it to a disabled folder, so it's out of sight/out of mind.

**Comment by jellz** [comment]
But in a disabled folder, it's not exactly out of sight. I understand what you mean in terms of OOP, but you can't change the prop for it without moving it into the working directory. 
I don't mind anymore though, I used ShayBox's solution, it's all good now.
