### ISSUE TITLE
Monitor does not work

### ISSUE THREAD

**Issue by InkoHX** [dirigeants/klasa#465]
### Describe the issue
Sending a message even though the loaded monitor does not work

### Code or steps to reproduce

1. save [nomention.js](https://github.com/dirigeants/klasa-pieces/blob/master/monitors/nomention.js) in `monitors` (I made sure that it was loaded)
2. Sending an mention, but does not respond

### Expected and actual behavior
Send mention

### Further details

- **discord.js version**: discordjs/discord.js@01476de58250761ffe5eedc9ee6c9782576ca043
- **node.js version**: v10.12.0
- **Klasa version**: dirigeants/klasa@de135656fe0bcd5f1dbc99e812717716dd187272
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash: dirigeants/klasa@de135656fe0bcd5f1dbc99e812717716dd187272

**Comment by KingDGrizzle** [comment]
That monitor seems to be existent from selfbot era, in which case, we do not support selfbots anymore (and neither does discord.js). Otherwise, if you edited it to log when your user was mentioned (so, monitor running on bot account), you need to pass in the `ignoreOthers` property in the constructor, and set it to false.

**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **Discord Server** instead of opening an issue – you'll be redirected there anyways.
