### ISSUE TITLE
MongoDB provider is causing an issue with built-in reload command

### ISSUE THREAD

**Issue by PyroTechniac** [dirigeants/klasa#613]
### Describe the issue
The [mongodb](https://github.com/dirigeants/klasa-pieces/blob/master/providers/mongodb.js) provider is causing an error when reloading everything with the built in reload command
### Code or steps to reproduce

```js
new Client({
    providers: {
        default: 'mongodb'
        mondodb: // Connection stuff here
    }
}).login(token)
```
run the built in `reload` command without providing any arguments

### Further details

- **discord.js version**: v12.0.0-dev
- **node.js version**: v11.10.0
- **Klasa version**: master
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash:
628fa2b5d75e677510adb9f83b7ecfefd6677192

**Comment by UnseenFaith** [comment]
Picture of error?

**Comment by PyroTechniac** [comment]
[2019-03-08 20:05:45] Uncaught Promise Error:
[2019-03-08 20:05:45] TypeError: Cannot read property 'update' of null
[2019-03-08 20:05:45]     at Settings._save (~\node_modules\klasa\src\lib\settings\Settings.js:396:31)
[2019-03-08 20:05:45]     at Settings._update (~\node_modules\klasa\src\lib\settings\Settings.js:350:15)

**Comment by kyranet** [comment]
Following the stack trace, the error is thrown here, `this.gateway.provider` is `null` as the error says:

https://github.com/dirigeants/klasa/blob/bec161bb4c1911fec248a017dbebee85879c02aa/src/lib/settings/Settings.js#L396

`Gateway#provider` (inherited from `GatewayStorage#provider`) is a getter:

https://github.com/dirigeants/klasa/blob/bec161bb4c1911fec248a017dbebee85879c02aa/src/lib/settings/GatewayStorage.js#L78-L80

This suggests a racecondition: when you reload a store (and also `[p]reload everything`, or just `[p]reload`, since `everything` is default, since they reload *all* stores), it removes all entries from the store and loads them back, this may take a while, since `require` is synchronous thus blocking (making the piece loading sequential), making the reload taking longer than the server is capable of. The `esm` branch uses experimental ESM, which is asynchronous (and reloads are faster!).

I suggest you to only reload the pieces you have changed, or the stores of the pieces you changed, avoiding to reload the providers in production.

**Comment by PyroTechniac** [comment]
I have further details to share

It seems like the only time this error occurs is when you have an init method that is creating a task on the client.schedule

**Comment by kyranet** [comment]
Yeah, you don't do that.

First off, before the settings branch merges, schedules should be created in the klasaReady even, in master you don't have Schedule populated while the pieces are initialising.

**Comment by PyroTechniac** [comment]
Alright, well thank you for the info, I will close this as it seems to be user error
